### ISSUE TITLE
Run to do

### ISSUE THREAD

**Issue by TApplencourt** [TApplencourt/G2_TestSet_CLI#12]
- Pour SiH2-3B1 avec la géométrie << expérimental >> il manque tout les CIPSI (10k puis 1M puis 1M_no_10k) en cc-pvdz et cc-pvtz.
- et pour les 1M puis 1M_on_10k  en cc-pVTZ, geo MP2 et Expérimental il manque ces 10 là :
  
  > > C2H4, C2H6, H3CO, N2H4, H2O2, Si2H, CH3C, H3CS, HOCl, SO2

**Comment by scemama** [comment]
2 SiH2_3B1 (-290.0099724853379)
2 Si2 (-577.7573638367707)
4 SiH2_3B1 (-290.0219052411219)
6 SiH2_3B1 (-290.0099724853379)
8 SiH2_3B1 (-290.0219052411219)
17 SiH2_3B1 ( -290.105019294369 , -4.114608414588605E-003)

:hankey:

**Comment by TApplencourt** [comment]
SiH2 triplet et LiH en DMC/HF/cc-pvDZ
SiH2_3B1_cc-pvdz_Experiment.HF.ez          E_loc :  -290.5308961230 +/-     0.0013460852
LiH_cc-pvdz_Experiment.HF.ez               E_loc :    -8.0675335873 +/-     0.0001224265

**Comment by TApplencourt** [comment]
22
CIPSI cc-pVTZ Experiment 1M_Dets_withoutPT2

# H3COH N2H4 H2O2 Si2H6 CH3Cl H3CSH HOCl SO2

23
CIPSI cc-pVTZ MP2 1M_Dets_withoutPT2

# H3COH N2H4 H2O2 Si2H6 CH3Cl H3CSH HOCl SO2

26
CIPSI cc-pVTZ Experiment 1M_Dets_NO_10k_Dets

# H3COH N2H4 H2O2 Si2H6 CH3Cl H3CSH HOCl SO2

27
CIPSI cc-pVTZ MP2 1M_Dets_NO_10k_Dets

# H3COH N2H4 H2O2 Si2H6 CH3Cl H3CSH HOCl SO2

64
DMC ANO-Roos-aug-DZ Experiment Hartree-Fock

# CH2_1A1 CS

65
DMC ANO-Roos-aug-TZ Experiment Hartree-Fock

# LiH BeH CH CH2_3B1 CH2_1A1 CH3 CH4 NH NH2 NH3 OH H2O HF SiH2_1A1 SiH2_3B1 SiH3 SiH4 PH2 PH3 H2S HCl Li2 LiF C2H2 C2H4 C2H6 CN HCN CO HCO H2CO H3COH N2 N2H4 NO O2 H2O2 F2 CO2 Na2 Si2 P2 S2 Cl2 NaCl SiO CS SO ClO ClF Si2H6 CH3Cl H3CSH HOCl

66
DMC cc-pVTZ Experiment Hartree-Fock

# LiH BeH CH CH2_3B1 CH2_1A1 CH3 CH4 NH NH2 NH3 OH H2O HF SiH2_1A1 SiH2_3B1 SiH3 SiH4 PH2 PH3 H2S HCl Li2 LiF C2H2 C2H4 C2H6 CN HCN CO HCO H2CO H3COH N2 N2H4 NO O2 H2O2 F2 CO2 Na2 Si2 P2 S2 Cl2 NaCl SiO CS SO ClO ClF Si2H6 CH3Cl H3CSH HOCl

70
DMC cc-pVDZ Experiment 1M_Dets_NO_1_Det

# CH2_1A1
